### ISSUE TITLE
Title line of the repository still points to old (deprecated) wiki

### ISSUE THREAD

**Issue by thmosqueiro** [smangul1/good.software#7]
Below the repository title, the description still has a link that points to the old wiki, misleading visitors. How about we remove that link? 

@smangul1 - I believe you're the only one who can edit it.

<img width="1026" alt="screen shot 2019-03-01 at 6 34 12 am" src="https://user-images.githubusercontent.com/5439895/53635766-21fc1500-3bec-11e9-82c2-7c8c63b3010f.png">

**Comment by smangul1** [comment]
done!
